version: '3'
services:
  minerva:
    build: ./
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0
    volumes:
      - ./data:/data/db
